# Generated by Django 2.1.7 on 2019-03-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190305_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='calend_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title_internal', models.CharField(help_text='Отображается только в адм.части', max_length=200, verbose_name='Название')),
            ],
        ),
    ]
