# Generated by Django 2.1.7 on 2019-03-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='date_str',
            field=models.CharField(default='', help_text='Отображается на сайте под Оглавлением', max_length=40, verbose_name='ДатаПроведения'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_external',
            field=models.CharField(default='', help_text='Отображается на сайте', max_length=200, verbose_name='Оглавление на сайте'),
        ),
    ]
