# Generated by Django 2.0.8 on 2019-03-12 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_calend_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='calend_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('date_str', models.CharField(max_length=255, verbose_name='Дата')),
                ('place_str', models.CharField(max_length=255, verbose_name='Место')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Соревнование в календаре',
                'verbose_name_plural': 'Соревнования в календаре',
            },
        ),
        migrations.CreateModel(
            name='calend_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=4, verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Годы',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='слаг')),
                ('url', models.URLField(blank=True, default='', verbose_name='URL')),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField(default='', help_text='Текст страницы', verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'страницы',
            },
        ),
        migrations.AlterModelOptions(
            name='calend_type',
            options={'verbose_name': 'Тип события в календаре', 'verbose_name_plural': 'Типы событий в календаре'},
        ),
        migrations.AddField(
            model_name='calend_item',
            name='calend_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.calend_type', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='calend_item',
            name='calend_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.calend_year', verbose_name='Год'),
        ),
    ]
