# Generated by Django 2.0.8 on 2019-04-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190312_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='mainpage',
            field=models.BooleanField(default=False, verbose_name='Главная'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_title',
            field=models.CharField(default='', max_length=200, verbose_name='заголовок'),
        ),
    ]
