# Generated by Django 2.0.8 on 2019-04-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190402_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='page',
            name='mainpage',
            field=models.BooleanField(default=False, verbose_name='Это Главная'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_title',
            field=models.CharField(default='', max_length=200, verbose_name='заголовок SEO'),
        ),
    ]
