# Generated by Django 2.0.8 on 2019-04-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190402_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='заголовок SEO'),
        ),
    ]
