# Generated by Django 2.0.8 on 2019-04-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20190402_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='заголовок SEO'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(blank=True, default='', help_text='Текст страницы', verbose_name='Текст'),
        ),
    ]
