# Generated by Django 2.0.8 on 2019-04-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190402_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='ExtraURL',
            field=models.URLField(blank=True, default='', verbose_name='URL'),
        ),
    ]
