# Generated by Django 2.0.8 on 2019-04-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_page_extraurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='ExtraURL',
            new_name='extraurl',
        ),
    ]
