# Generated by Django 2.0.8 on 2019-04-02 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20190402_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(blank=True, default='', upload_to='', verbose_name='Изображение')),
                ('seo_title', models.CharField(blank=True, default='', max_length=200, verbose_name='заголовок Alt')),
                ('url', models.URLField(blank=True, default='', verbose_name='URL')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='extraurl',
            field=models.URLField(blank=True, default='', verbose_name='ExtraURL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='photo',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Page', verbose_name='Страница'),
        ),
    ]
